# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 20, 191, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.make_gif = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.make_gif.setObjectName("make_gif")
        self.verticalLayout.addWidget(self.make_gif)
        self.make_mp4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.make_mp4.setObjectName("make_mp4")
        self.verticalLayout.addWidget(self.make_mp4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 301, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 150, 301, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 341, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 250, 161, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 321, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(390, 10, 421, 51))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(390, 110, 331, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 150, 301, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(390, 210, 321, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 250, 301, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(240, 480, 311, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 310, 161, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 260, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 320, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 60, 301, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 380, 331, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 420, 311, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(390, 310, 321, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(390, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(390, 420, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)                  # label_12
        self.lineEdit_8.setGeometry(QtCore.QRect(530, 410, 161, 41))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)                  # label_13
        self.lineEdit_9.setGeometry(QtCore.QRect(530, 350, 161, 41))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.make_gif.setText(_translate("MainWindow", "Зробити gif"))
        self.make_mp4.setText(_translate("MainWindow", "Зробити mp4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Зображення"))
        self.label_2.setText(_translate("MainWindow", "Допустима висота польоту, м."))
        self.label_3.setText(_translate("MainWindow", "Фокусна відстань об\'єктива, мм."))
        self.label_4.setText(_translate("MainWindow", "Геометрія  фотосенсора, мм:"))
        self.label_5.setText(_translate("MainWindow", "Заряд батареї на момент запуску, %"))
        self.label_6.setText(_translate("MainWindow", "Витрата заряду на фото, %"))
        self.label_7.setText(_translate("MainWindow", "Витрата заряду на 100м, %"))
        self.pushButton.setText(_translate("MainWindow", "Вибрати шлях"))
        self.label_8.setText(_translate("MainWindow", "Висота матриці"))
        self.label_9.setText(_translate("MainWindow", "Ширина матриці"))
        self.label_10.setText(_translate("MainWindow", "Вибрати зображення мапи"))
        self.pushButton_2.setText(_translate("MainWindow", "Вибрати мапу"))
        self.label_11.setText(_translate("MainWindow", "Масштаб мапи, м:"))
        self.label_12.setText(_translate("MainWindow", "Висота мапи"))
        self.label_13.setText(_translate("MainWindow", "Ширина мапи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Вхідні дані"))

